#!/usr/env/bin bash

#GLOBAL VARS
REPO=https://github.com/TrainingAfternoon/cltools
RAW_REPO=https://github.com/TrainingAfternoon/cltools
BRANCH=/main

#install xcodedarkhc vim coloration
cd $HOME/.vim/colors
curl -sL https://raw.githubusercontent.com/arzg/vim-colors-xcode/master/colors/xcodedarkhc.vim >> xcodedarkhc.vim

#Make bin directory if necessary; move to bin
cd $HOME
if [ ! -d "bin" ]
then
    mkdir bin
fi
cd $HOME/bin

#DEPRECATED
#Download cltool files via git clone
#if [ ! -d ".git" ]
#then
#    if [ -z $(ls) ]
#    then #If the dir is empty, we can just dump output into . (current dir)
#        git clone $REPO .
#    else
#        #If bin is nonempty, we must be nondestructive so we have to dump and pump 
#        git clone $REPO
#        mv cltools/* .
#        rm -rf cltools
#    fi
#fi

#Download cltool executables via cURL
curl -L $(REPO)/main/resources/files.txt >> files.txt #List of all executables
IFS=$'\n'
FILES=($(cat files.txt)) #Technically redundant... Move into for loop expression?
for FILE in $FILES
do
    curl -L $(RAW_REPO)/$(BRANCH)/$(FILE) >> $(FILE)
done
rm files.txt #Clean up after ourselves


#Perform set up on Windows Terminal if it exists
#First, check if running on a windows system by checking if /mnt/c exists
if [ -d "/mnt/c" ]
then
    cd "/mnt/c/Program Files (x86)"
    mkdir cltools
    cd cltools
    curl -L https://media2.giphy.com/media/Yc65Sk2Hwkzgk/giphy.gif > swing.gif
fi

#TODO: figure out how to scrape windows home directory, which we need to get to WinTerm home 

#make sure bin is in path & executable
export PATH=$PATH:$HOME/bin
cd ..
chmod -R u+x bin
