#!/usr/env/bin bash

#GLOBAL VARS
REPO=https://github.com/TrainingAfternoon/cltools

#install xcodedarkhc vim coloration
cd $HOME/.vim/colors
curl -sL https://raw.githubusercontent.com/arzg/vim-colors-xcode/master/colors/xcodedarkhc.vim >> xcodedarkhc.vim

#Make bin directory if necessary; move to bin
cd $HOME
if [ ! -d "bin" ]
then
    mkdir bin
fi
cd $HOME/bin

#Download cltool files
if [ ! -d ".git" ]
then
    if [ -z $(ls) ]
    then #If the dir is empty, we can just dump output into . (current dir)
        git clone $REPO .
    else
        #If bin is nonempty, we must be nondestructive so we have to dump and pump 
        git clone $REPO
        mv cltools/* .
        rm -rf cltools
    fi
fi

#make sure bin is in path & executable
export PATH=$PATH:$HOME/bin
cd ..
chmod -R u+x bin
