#!/usr/bin/env bash

#As the name implies, ls output is NOT always safe to parse, and this should probably be replaced at some point
UNSAFE_ZIS=$(ls | grep Zone.Identifier)

for FILE in $UNSAFE_ZIS
do
    rm $FILE
    echo $FILE" removed!"
done

